### ISSUE TITLE
Problem sending messages

### ISSUE THREAD

**Issue by Fale** [evgeni/fedora-mutt-patched#1]
When I try to send a message, this comes out:

```
Sending message...sh: /usr/bin/mutt_dotlock: No such file or directory
Couldn't lock /home/fale/sent?                                        
```

I guess it's not a config file, because if I go back to the official Fedora mutt package everything works.

**Comment by evgeni** [comment]
Hi @Fale,

I think I have seen this once, but cannot remember the details. :(

Which mbox type are you using? Could you provide a minimal muttrc which triggers this problem?

mutt_dotlock is removed in the original Fedora mutt package too, so I would actually expect it to fail there identically.

**Comment by evgeni** [comment]
Okay, I can reproduce this with

```
mutt -F /dev/null
…
Sending message...sh: /usr/bin/mutt_dotlock: No such file or directory
Couldn't lock /home/remote/egolov/sent?
```

So no user-specific config is involved.
OK: mutt-1.5.24-1.fc23.x86_64
not-OK: mutt-patched-5:1.5.24-2.fc23.x86_64

Investigating why this happens, thanks.

**Comment by Fale** [comment]
Hi,
you can find my config at https://github.com/Fale/muttrc :)

**Comment by evgeni** [comment]
@Fale there, fixed. copr pushed too :)

**Comment by Fale** [comment]
thanks :)
